### ISSUE TITLE
User Story 2 - Friend Profile Page

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#1]
## Value proposition

As a user
I want to be able to see the full friend contact Page with detail information
So that I can get all informations about my friend

## Description

![US2](https://user-images.githubusercontent.com/123883905/235938695-0529f0fb-510a-4f4f-9914-1a5d66ff2982.png)

## Acceptance criteria

- [ ]  Clicking an friend from the list shows the detail page
- [ ]  The friend profile icon is displayed 
- [ ]  The friend first name is displayed 
- [ ]  The friend last name is displayed 
- [ ]  The friend nickname is displayed 
- [ ]  The friend birthday is displayed 
- [ ]  The friend friendship status is displayed 
- [ ]  The friend hobbies is displayed 
- [ ]  The friend city is displayed 
- [ ]  The friend contact options: {Phone number, Signal, Telegram, Mail, Instagram, Twitter, LinkedIn}
 is displayed 
- [ ]  Clicking the back-button shows the list view

## Tasks

- [ ] task 1
- [ ] create a branch 
- [ ] Create the component FriendPageDetails
- [ ] FriendPageDetails props: image, ....
- [ ] Create the page pages/friend-pages/[slug] that 
  renders FriendPageDetails
- [ ] Read the query parameter slug from next/router
- [ ] Use the slug to find the friends to display

Size:

**Comment by HenrikeStahlhut** [comment]
>  The friend hobbies is displayed
>  The friend birthday is displayed

Hi Calle, i would change _hobbies_ to _communality_, since thats whats displayed in your wireframe. 
I also think you forgot to add the birthday to your wireframe and the point "friends since" in the description :) Maybe you could add that. 
Otherwise great user story, i really like the design and idea!

**Comment by cmgoersch** [comment]
THX Henny. 
I reconsidered and revised the content.

**Comment by JessicaLoers** [comment]
**Hey @cmgoersch ✌️**
very nice app idea and User Story. 
Also nice that Gundula Gause is a friend of yours. 😁

Here's a just really picky suggestion about the Value Proposition. 
This is not to annoy you, but to serve as an example that we can write the Value Proposition even more precisely. And you can really train that. 🏋️‍♀️

## Value Proposition 
**As a user**
**I want to** to access a comprehensive contact page for my respective friend,
**So that I can** easily obtain all relevant information about them.

Of course, you don't have to rewrite this user story. As it is now, it's already very, very great.
