### ISSUE TITLE
[US6] Delete-Contact

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#10]
## Value proposition

As a user
I would like to be able to delete contacts
not to have to keep unnecessary or old contacts

## Description

![Image](https://user-images.githubusercontent.com/123883905/238900961-e5ce4e13-d317-4c9a-b620-43886c5f268a.png)

## Acceptance criteria

- [ ] on the "edit contact page" there should be a "remove contact" button
- [ ] when the button is pressed a window with "really delete" should pop up
- [ ] by clicking the button the contact should disappear from the contact book

## Tasks

- [ ] create a branch
- [ ] create a "remove contact" button on each "edit contact" page
- [ ] Write the logic that deletes the respective contact
- [ ] Make sure that a "security notice" "really delete permanently?" is displayed which must be confirmed.

Size:

Medium

**Comment by CJAkkuec** [comment]
Looking good! I'd probably suggest that the button doesn't need to say "remove contact" but that a big red button with an "x" on it essentially implies what's going to happen if it is pressed. ;)
