### ISSUE TITLE
[US7] Search-Contact

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#11]
## Value proposition

As a user
I would like to have a search bar displayed
to find single friends faster in my big contact book

## Description

![Image](https://user-images.githubusercontent.com/123883905/238952536-8605f368-f149-4143-94a8-78921dae41e0.png)

## Acceptance criteria

- [ ] On the contact page I see a search bar
- [ ] when I enter names in this search bar I see only the matching contacts 

## Tasks

- [ ] create a branch
- [ ] create a search bar on the contact page
- [ ] Make sure that the contacts not present in the search are hidden

Size:

Medium

**Comment by frank12421** [comment]
Hi Calle, LGTM 🚀
