### ISSUE TITLE
[US8] Birthday-List

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#12]
## Value proposition

As a user 
I would like to have a list of all birthday stars in my contact list
in order to never miss a birthday again and become an even better friend

## Description

![Image](https://user-images.githubusercontent.com/123883905/238968310-1b892665-4538-4ae6-b038-fe91eca5e2f3.png)

## Acceptance criteria

- [ ] A button with the name "birthdays" should be visible on the "start page" and in the "contact book".
- [ ] On the page "Birthdays" a list of the 5-10 upcoming birthdays by days in the year is visible. 
- [ ] For each tag you can see profile picture, nickname, date of birth and "how many days until birthday".

## Tasks

- [ ] create a branch
- [ ] Create a "Birthdays" button on the home page and contact book
- [ ] Create the "Birthdays" page
- [ ] route all existing data to the "Birthdays" page and folder over all data.
- [ ] Read all birthdays and display the last 5-10 contacts by birthdays among them 
- [ ] Show the distance as a number to the birthday for each entry

Size:

Large

**Comment by MerleMak** [comment]
HI Calle,
This looks good! I love the value Proposition :D 
The Birthday Button should definitely be a component, you could add that to the tasks.
I am not sure what you mean by the last task. Could you specify that point?
Other than that this looks like a big but very nice Userstory! Good job!
