### ISSUE TITLE
[US9] Statistics

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#13]
## Value proposition

As a user
I would like to see some statistics 
to see my sociability with my friends in numbers

## Description

![Image](https://user-images.githubusercontent.com/123883905/238973432-a7ccb3a4-04e1-4a00-ace0-54aa8fc60d4f.png)

## Acceptance criteria

- [ ] A button with the name "Statistics" should be visible on the "start page" 
- [ ] On the "Statistics" page a list of different evaluations is shown:
a) which contact was reached the most often
b) how often did you use the random function
c) how often did you try to call someone / how often did you reach someone
d) how often did you try to reach someone on their birthday in the last 356 days?

## Tasks

- [ ] create a branch
- [ ] Create a "Statistics" button on the home page
- [ ] Create the "Statistics" page
- [ ] route all existing data to the "Statistics" page and map over all data.
- [ ] Show the following 4 pieces of information:
a) the contact that was reached the most often
b) how often the random function was used
c) how often was tried to reach a friend/how often was it successful
d) how many times in the last 356 days someone tried to reach you on your birthday

Size:

Large

**Comment by MerleMak** [comment]
Hi Calle,
Very nice Userstory.
Please specify the last point of your Tasks. I think you mean you tried to reach someone on their birthday? Because otherwise you wouldn't have to check on the last 365 days but only on your specific birthday, no?
Are you using a global state management library, like Zustand? It might be very very helpful for this Userstory, as you will need to access a lot of different data. 
Check it out here: https://docs.pmnd.rs/zustand/getting-started/introduction
I am excited to see this build! Good luck :))

**Comment by cmgoersch** [comment]
Thanks for the comment. I have made the evaluation more precise. It is not yet set in stone. Perhaps someone can think of even more exciting evaluations. First of all, I would like to implement the module.

Thank you. I hope so goes the UserStorry by the release. :)****

**Comment by HenrikeStahlhut** [comment]
LGTM ✌🏻
