### ISSUE TITLE
[US10] Button Circle & Colors

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#15]
## Value proposition

As a user
I would like to see the contact options arranged in a circle around the Nuter icon 
to easily reach the corresponding contact possibility with the right thumb

## Description

![Image](https://user-images.githubusercontent.com/123883905/239773502-357927f4-9428-4667-82e0-c598710f7488.png)

## Acceptance criteria

- [ ] All icons are arranged in a circle around the user icon
- [ ] all icons have a color corresponding to the icon
- [ ] all icons link to the corresponding contact platform or to the phone or mail

## Tasks

- [ ] create a branch
- [ ] Arrange the buttons in a circle around the user icon
- [ ] Include a link to the platform to which the corresponding button is linked to
- [ ] Build a counter that counts each button click and attributes it to the respective contact

Size:

Large

**Comment by frank12421** [comment]
Hi Calle, LGTM
Have fun 🫥
