### ISSUE TITLE
[US11] Ten reasons why

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#16]
## Value proposition

As a user
I would like to see a button on the home page and from there a page with "10 reasons to sign up".
to make it easier for users with an inhibition to find a good reason to contact a loved one from the contact list!

## Description

![Image](https://user-images.githubusercontent.com/123883905/239774179-22db5955-96f7-4fd2-bdaf-2d36beaca3e3.png)

## Acceptance criteria

- [ ] There is a button "10 reasons to sign up" on the home page
- [ ] There is a page with 10 good reasons to sign up
- [ ] On the "Good reasons" page there is a "back" button that leads back to the coffin page

## Tasks

- [ ] create a branch
- [ ] Create a "10 reasons to sign up" button on the home page.
- [ ] Create the "Good reasons" page and place the text with the 10 good reasons to sign up there. You can have ChatGPT write the reasons. This will be fun!
- [ ] Add a "Back" button on the page that leads back to the home page

Size:

Medium

**Comment by HenrikeStahlhut** [comment]
LGTM
