### ISSUE TITLE
[US12] Contact Counter

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#17]
## Value proposition

As a user
I would like to see for each contact when and how often he was contacted
to get an overview of how often I have contacted my fantastic circle of friends and not to forget anyone

## Description

![Image](https://user-images.githubusercontent.com/123883905/239774647-e13248e1-59c4-4378-8ac3-a64fdd524b5d.png)

## Acceptance criteria

- [ ] I can see on the contact overview under each contact when the last contact was
- [ ] I see on each contact page how often and when was the last contact.

## Tasks

- [ ] Create a branch
- [ ] take the evaluation data and place a counter with "last contact: [?]" under each contact
- [ ] create a counter with "last contact [?]" on every single contact page 

Size:

Large !? ;)

**Comment by antoniatandler** [comment]
this is such a cool idea! looks good to me 🤩
