### ISSUE TITLE
User Story 1 - List of Friends/Contacts/Directory

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#2]
## Value proposition

As a user
I want to see a list of my contacts
in order to can get an overview of all my friends

## Description

![US1](https://user-images.githubusercontent.com/123883905/235939584-82c00adc-4fb0-436e-aa82-17236881d0e8.png)

## Acceptance criteria

- [ ] All friends are displayed as a list 
- [ ] Each friends image is displayed 
- [ ] Each friends Name is displayed 

## Tasks

- [ ] create a branch 
- [ ] define Global Styles
- [ ] Fetch all friends with SWR in pages/index.js
- [ ] Create the component FriendPages to render a list
- [ ] FriendPages props: pages
- [ ] Create the component FriendsPagePreview
- [ ] FriendsPagePriview props: image, first name, Last name, Nickname

Size:

**Comment by mbosselmann** [comment]
Hi Calle,
you rock! 🪨 I have some remarks for you to consider before moving further:

## Value Proposition
- "in order to can get an overview of all my friends" - "can" can be removed


## Tasks
- "Fetch all friends with SWR in pages/index.js" - Do you plan to start with a db.js where you safe your example data? Then you do not need to fetch the data with SWR, you can import the example data and work with it directly. :) Therefore, I would recommend as task "- [ ] create a db.js with example friends"

And if you do not want to set a size for your user story (this is optional) then you can remove this part. With size you can decide what you think is the complexity of your user story (usually small, medium or large).

I hope this does help! Feel free to ask if you have questions. :)

**Comment by cmgoersch** [comment]
Thank you very much. I have taken over all change requests. I hope so you give me a release :)
