### ISSUE TITLE
[US15] Database connection

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#20]
## Value proposition

As a user
I want my information to be kept secure
to be able to access my collected information in the long term

## 

- [ ] All data are always and everywhere available even after a reload

## Tasks

- [ ] create a branch
- [ ] Create a database on MongoDB Cloud
- [ ] Swap the Local Storage for the connection to MongoDB
- [ ] Make sure that all data can be entered and changed there

Size:

Large
