### ISSUE TITLE
[US5] Edit-Contact

### ISSUE THREAD

**Issue by cmgoersch** [cmgoersch/capstone-project#7]
## Value proposition

As a user 
I would like to be able to edit the data of individual contacts
to subsequently change and update information

## Description

![Image](https://user-images.githubusercontent.com/123883905/237135445-944f9afd-9ed0-46fa-91e8-dd965414e58d.png)

## Acceptance criteria

- [ ] the form with all entered information is visible
- [ ] the entries can be changed
- [ ] a save button is visible 
- [ ] the data can be saved and the button leads back to the profile page
- [ ] create a "change data" button in the profile page 

## Tasks

- [ ] create a branch
- [ ] create the page with the form
- [ ] import the existing data from the respective dataset into the form
- [ ] create a "save" button
- [ ] create a "change data" button in the profile page 

Size:

Large

**Comment by t0bbl** [comment]
lgtm

**Comment by ketnek** [comment]
Hey Calle,
nice job.
I like the suggestions I get, when changing the profile image.
One suggestion I have. It would be nicer to come back to the single profile page when I clicking the back or save button in the edit modus  instead of coming back to all friends.
